export default {
  POST_CAMPAIGN: "POST_CAMPAIGN",
  UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
  DELETE_CAMPAIGN: "DELETE_CAMPAIGN",
  ACTIVATE_CAMPAIGN: "ACTIVATE_CAMPAIGN",
  GET_CAMPAIGNS: "GET_CAMPAIGNS",
  REORDER_CAMPAIGNS: "REORDER_CAMPAIGNS",
  GET_CAMPAIGN: "GET_CAMPAIGN",
  GET_COUNTRIES: "GET_COUNTRIES",
  GET_CURRENCIES: "GET_CURRENCIES",
  GET_CONDITION_TYPES: "GET_CONDITION_TYPES",
  GET_ACTION_TYPES: "GET_ACTION_TYPES",
};
